export const DEFAULT_SONGS = [
  { id: "stand-by-me", title: "Stand By Me", artist: "Ben E. King" },
  { id: "viva-la-vida", title: "Viva La Vida", artist: "Coldplay" },
  { id: "dreams", title: "Dreams", artist: "Fleetwood Mac" },
  { id: "saturday-night", title: "Saturday Night", artist: "" },
  { id: "valerie", title: "Valerie", artist: "Amy Winehouse" },
  { id: "will-we-talk", title: "Will We Talk?", artist: "Sam Fender" },
  { id: "still-the-one", title: "Still The One", artist: "Shania Twain" },
  { id: "man-i-need", title: "Man I Need", artist: "Olivia Dean" },
  { id: "she-will-be-loved", title: "She Will Be Loved", artist: "Maroon 5" },
  { id: "dancing-queen", title: "Dancing Queen", artist: "ABBA" },
  { id: "love-story", title: "Love Story", artist: "Taylor Swift" },
  { id: "cant-take-my-eyes-off-you", title: "Can’t Take My Eyes Off You", artist: "Frankie Valli" },
  { id: "sit-down", title: "Sit Down", artist: "James" },
  { id: "the-way-you-make-me-feel", title: "The Way You Make Me Feel", artist: "Michael Jackson" },
  { id: "believe", title: "Believe", artist: "Cher" },
  { id: "bet-you-look-good-on-the-dancefloor", title: "Bet You Look Good On The Dancefloor", artist: "Arctic Monkeys" },
  { id: "sex-on-fire", title: "Sex On Fire", artist: "Kings of Leon" },
  { id: "morning-glory", title: "Morning Glory", artist: "Oasis" },
  { id: "dancing-in-the-moonlight", title: "Dancing In The Moonlight", artist: "Toploader" },
  { id: "17-going-under", title: "17 Going Under", artist: "Sam Fender" },
  { id: "teenage-dirtbag", title: "Teenage Dirtbag", artist: "Wheatus" },
  { id: "dakota", title: "Dakota", artist: "Stereophonics" },
  { id: "summer-of-69", title: "Summer Of 69", artist: "Bryan Adams" },
  { id: "dancing-in-the-dark", title: "Dancing In The Dark", artist: "Bruce Springsteen" },
  { id: "shut-up-and-dance", title: "Shut Up And Dance", artist: "Walk the Moon" },
  { id: "pink-pony-club", title: "Pink Pony Club", artist: "Chappell Roan" },
  { id: "yellow", title: "Yellow", artist: "Coldplay" },
  { id: "all-the-small-things", title: "All The Small Things", artist: "blink-182" },
  { id: "angels", title: "Angels", artist: "Robbie Williams" },
  { id: "simply-the-best", title: "Simply The Best", artist: "Tina Turner" },
  { id: "year-3000", title: "Year 3000", artist: "Busted" },
  { id: "dont-look-back-in-anger", title: "Don’t Look Back In Anger", artist: "Oasis" },
  { id: "mr-brightside", title: "Mr Brightside", artist: "The Killers" },
  { id: "country-roads", title: "Country Roads", artist: "John Denver" },
  { id: "first-dance", title: "First Dance", artist: "" },
  { id: "brown-eyed-girl", title: "Brown Eyed Girl", artist: "Van Morrison" },
  { id: "teenage-dream", title: "Teenage Dream", artist: "Katy Perry" },
  { id: "shotgun", title: "Shotgun", artist: "George Ezra" },
  { id: "free-fallin", title: "Free Fallin’", artist: "Tom Petty" },
  { id: "wagon-wheel", title: "Wagon Wheel", artist: "Darius Rucker" },
  { id: "what-makes-you-beautiful", title: "What Makes You Beautiful", artist: "One Direction" },
  { id: "500-miles", title: "500 Miles", artist: "The Proclaimers" },
  { id: "perfect", title: "Perfect", artist: "Ed Sheeran" },
  { id: "the-middle", title: "The Middle", artist: "Jimmy Eat World" },
  { id: "everywhere", title: "Everywhere", artist: "Fleetwood Mac" }
];

export const DEFAULT_SETS = [
  {
    id: "set-1",
    name: "Set 1",
    songIds: [
      "stand-by-me",
      "viva-la-vida",
      "dreams",
      "saturday-night",
      "valerie",
      "will-we-talk",
      "still-the-one",
      "man-i-need",
      "she-will-be-loved",
      "dancing-queen",
      "love-story",
      "cant-take-my-eyes-off-you",
      "sit-down",
      "the-way-you-make-me-feel",
      "believe",
      "bet-you-look-good-on-the-dancefloor",
      "sex-on-fire"
    ]
  },
  {
    id: "set-2",
    name: "Set 2",
    songIds: [
      "morning-glory",
      "dancing-in-the-moonlight",
      "17-going-under",
      "teenage-dirtbag",
      "dakota",
      "summer-of-69",
      "dancing-in-the-dark",
      "shut-up-and-dance",
      "pink-pony-club",
      "yellow",
      "all-the-small-things",
      "angels",
      "simply-the-best",
      "year-3000",
      "dont-look-back-in-anger",
      "mr-brightside",
      "country-roads"
    ]
  }
];
